"""Public contracts for frame-aligned kinematics analysis."""

from .protocols import (
    CancellationProbe,
    DerivativeOperator,
    FitOperator,
    KinematicsEngine,
    ProgressReporter,
    SeriesBuilder,
)
from .types import (
    DerivativeConfig,
    DerivativeMethod,
    EdgePolicy,
    FitModel,
    FitRequest,
    FitResult,
    FitStatus,
    GapPolicy,
    KinematicsBundle,
    ProcessingStep,
    SampleSeries,
)
from .validation import (
    StaleSourceRevisionError,
    cadence_relative_deviation,
    contiguous_valid_segments,
    derivative_unit,
    fit_parameter_names,
    fit_parameter_units,
    fit_sample_mask,
    require_current_revision,
    require_uniform_cadence,
)

__all__ = [
    "CancellationProbe",
    "DerivativeConfig",
    "DerivativeMethod",
    "DerivativeOperator",
    "EdgePolicy",
    "FitModel",
    "FitOperator",
    "FitRequest",
    "FitResult",
    "FitStatus",
    "GapPolicy",
    "KinematicsBundle",
    "KinematicsEngine",
    "ProcessingStep",
    "ProgressReporter",
    "SampleSeries",
    "SeriesBuilder",
    "StaleSourceRevisionError",
    "cadence_relative_deviation",
    "contiguous_valid_segments",
    "derivative_unit",
    "fit_parameter_names",
    "fit_parameter_units",
    "fit_sample_mask",
    "require_current_revision",
    "require_uniform_cadence",
]
